-- Migration 006: Weekly Wrapped snapshots
-- Stores a frozen-in-time payload per week, generated by Cloud Scheduler each Friday 22:00.

CREATE TABLE IF NOT EXISTS weekly_wrapped (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	week_start DATE NOT NULL,
	week_end DATE NOT NULL,
	generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	payload JSONB NOT NULL,
	UNIQUE (week_start)
);

CREATE INDEX IF NOT EXISTS idx_weekly_wrapped_week_start ON weekly_wrapped (week_start DESC);
