-- Migration 012: Friday talk-show episodes.
--
-- Once per week, three AI reporter personas (Marcel, Sophie, Frank)
-- co-host a 3–5 minute round-up of the office FIFA week. The script
-- is generated by a single Claude call, then the per-speaker turns
-- are TTS'd and concatenated into one mp3.
--
-- One row per ISO calendar week, keyed on the Monday of that week
-- (mirroring `weekly_wrapped`). `audio_url` is nullable because text
-- generation and TTS run as separate steps — a row can exist with the
-- script but no audio if the TTS step is still pending or failed and
-- is being retried.

CREATE TABLE IF NOT EXISTS talkshow_episodes (
	week_start    DATE PRIMARY KEY,
	week_end      DATE NOT NULL,
	script_json   JSONB NOT NULL,
	audio_url     TEXT,
	generated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_talkshow_episodes_generated_at
	ON talkshow_episodes (generated_at DESC);
